sonar.organization=ti-tecnologico-de-monterrey-oficial

sonar.projectKey=ti-tecnologico-de-monterrey-oficial_signing-service
sonar.projectName=signing-service

sonar.sourceEncoding=UTF-8

# Codigo fuente
sonar.sources=src,server.js

# Pruebas
sonar.tests=src
sonar.test.inclusions=src/**/*.test.js

sonar.exclusions=coverage/**,node_modules/**,logs/**
sonar.coverage.exclusions=src/**/*.test.js,src/test-fixtures/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Esperar resultado del Quality Gate
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300


